In [25]:
#Importing the panda module as pd
import pandas as pd

In [26]:
#Creating the data custom dataframe
pd.DataFrame({'Name': ['Unish', 'Riyan'],
            'Location': ['Samjana_Chowk', 'Jhiljhile']})

    Name       Location
0  Unish  Samjana_Chowk
1  Riyan      Jhiljhile

In [27]:
#Creating another custom dataframe with custom indexs
pd.DataFrame({'Ram': ['Very good', 'Nice'],
             'Sita': ['Awaful', 'Not Nice']}, index = ['Movie 1', 'Movie 2'])

               Ram      Sita
Movie 1  Very good    Awaful
Movie 2       Nice  Not Nice

In [28]:
#Creating a custom series
pd.Series([1,2,3,4,5,6])

0    1
1    2
    ..
4    5
5    6
Length: 6, dtype: int64

In [29]:
#Creating a custom series with a unique student marks with proper labeling of attribute
pd.Series([79, 89, 90], name = 'Marks', index = ['Std1', 'Std2', 'Std3'])

Std1    79
Std2    89
Std3    90
Name: Marks, dtype: int64

In [35]:
#Loading the dataset
dataframe = pd.read_csv('Breast_cancer_dataset.csv')
dataframe

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
..      ...       ...  ...                      ...          ...
567  927241         M  ...                  0.12400          NaN
568   92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [42]:
#Displaying the custom number of columns and rows
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)

In [43]:
dataframe

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,...,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,...,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,...,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,...,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,...,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,...,0.4000,0.1625,0.2364,0.07678,NaN
...,...,...,...,...,...,...,...,...,...,...,...
564,926424,M,21.56,22.39,142.00,...,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,...,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,...,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,...,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,...,0.0000,0.0000,0.2871,0.07039,NaN

In [44]:
#Mathmatical description of the dataframe
dataframe.describe()

,id,radius_mean,texture_mean,perimeter_mean,area_mean,...,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
count,5.690000e+02,569.000000,569.000000,569.000000,569.000000,...,569.000000,569.000000,569.000000,569.000000,0.0
mean,3.037183e+07,14.127292,19.289649,91.969033,654.889104,...,0.272188,0.114606,0.290076,0.083946,NaN
std,1.250206e+08,3.524049,4.301036,24.298981,351.914129,...,0.208624,0.065732,0.061867,0.018061,NaN
min,8.670000e+03,6.981000,9.710000,43.790000,143.500000,...,0.000000,0.000000,0.156500,0.055040,NaN
25%,8.692180e+05,11.700000,16.170000,75.170000,420.300000,...,0.114500,0.064930,0.250400,0.071460,NaN
50%,9.060240e+05,13.370000,18.840000,86.240000,551.100000,...,0.226700,0.099930,0.282200,0.080040,NaN
75%,8.813129e+06,15.780000,21.800000,104.100000,782.700000,...,0.382900,0.161400,0.317900,0.092080,NaN
max,9.113205e+08,28.110000,39.280000,188.500000,2501.000000,...,1.252000,0.291000,0.663800,0.207500,NaN

In [47]:
#Displaying the specific column
dataframe.diagnosis

0      M
1      M
2      M
3      M
4      M
      ..
564    M
565    M
566    M
567    M
568    B
Name: diagnosis, Length: 569, dtype: object

In [48]:
#another way of accessing a specific column
dataframe['id']

0        842302
1        842517
2      84300903
3      84348301
4      84358402
         ...
564      926424
565      926682
566      926954
567      927241
568       92751
Name: id, Length: 569, dtype: int64

In [52]:
#Accessing the top 9 rows of the dataframe Default value is 5
dataframe.head(9)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,...,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,...,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,...,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,...,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,...,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,...,0.4000,0.1625,0.2364,0.07678,NaN
5,843786,M,12.45,15.70,82.57,...,0.5355,0.1741,0.3985,0.12440,NaN
6,844359,M,18.25,19.98,119.60,...,0.3784,0.1932,0.3063,0.08368,NaN
7,84458202,M,13.71,20.83,90.20,...,0.2678,0.1556,0.3196,0.11510,NaN
8,844981,M,13.00,21.82,87.50,...,0.5390,0.2060,0.4378,0.10720,NaN

In [53]:
#Accessing the last 9 rows of the dataframe
dataframe.tail(9)

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,...,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
560,925292,B,14.05,27.15,91.38,...,0.1326,0.1048,0.2250,0.08321,NaN
561,925311,B,11.20,29.37,70.67,...,0.0000,0.0000,0.1566,0.05905,NaN
562,925622,M,15.22,30.62,103.40,...,1.1700,0.2356,0.4089,0.14090,NaN
563,926125,M,20.92,25.09,143.00,...,0.6599,0.2542,0.2929,0.09873,NaN
564,926424,M,21.56,22.39,142.00,...,0.4107,0.2216,0.2060,0.07115,NaN
565,926682,M,20.13,28.25,131.20,...,0.3215,0.1628,0.2572,0.06637,NaN
566,926954,M,16.60,28.08,108.30,...,0.3403,0.1418,0.2218,0.07820,NaN
567,927241,M,20.60,29.33,140.10,...,0.9387,0.2650,0.4087,0.12400,NaN
568,92751,B,7.76,24.54,47.92,...,0.0000,0.0000,0.2871,0.07039,NaN